# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    my.listener:
        class: AppBundle\EventListener\Listener
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    app.namer:
        class: AppBundle\Service\Namer
    acme.aws_credentials:
        class: Aws\Credentials\Credentials
        arguments: [%aws_access_key_id%, %aws_secret_access_key%]

    acme.aws_s3:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                #key: %aws_access_key_id%
                #secret: %aws_secret_access_key%
                region: %aws_s3_region%
                version: %aws_sdk_version%
                credentials: @acme.aws_credentials